apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: first-pod
spec:

  replicas: 3
  selector:
   matchLabels:
    env: dev

  template:
    metadata:
      name: container-1
      labels:
        env: dev
    spec:
      containers:
       - name: first-container
         image: nginx
