apiVersion: apps/v1
kind: Deployment
metadata:
     name: first-deployment
spec:
     replicas: 3
     selector:
       matchLabels:
           a: america
     template:
        metadata:
          labels:
             a: america
        spec:
           containers:
             - name: container-1
               image: httpd
               envFrom:
               - configMapRef:
                       name: second-cm
